""" writer.py.
This is the code for formatting and writing the output file.
It gets its data from an iterator of PpTok objects generated by
the various source files.
"""

from __future__ import annotations

import re
import textwrap


from pcpp.common import *
from pcpp.tokens import *

class Writer:
    """ Object which accepts an iterator of PpTok's and writes
    to the output file.
    """

    def __init__(self, prep: PreProcessor):
        self.prep = prep
        self.lexer = prep.lexer

    def write(
            self,
            toks: Callable[[], PpTok],      # Generated by Source files
            out: TextIO,                    # Output file, already open
            ):
        self.tokens = toks
        prep = self.prep

        tok: PpTok
        tok = None
        prevtoks = self.PrevToks()

        # OutLoc objects currently in use, ending with the most recent.
        outlocs: Stack[OutLoc] = Stack()

        outloc: OutLoc              # Current location, in current Source.
        outloc = None
        callback: LocalCallback
        callback = None

        ''' Overall strategy:
        self.write() takes an iterable `tokens` of PpTok's, and writes text
            to the output file `out`, using output().

        The input tokens come from the top level Source.  It has already done
            translation phases 1 through 4 (C99 5.1.1.2 pp 1.1-1.4), which
            means that #include'd files are likewise translated.

        There are no directives coming from the Source, except as enabled by
            various passthru command options.

        As the Standard considers the preprocessor as merely translation phase
            4, only actual preprocessing tokens are involved.  Whitespace is
            no longer relevant.  In fact, it is mostly irrelevant during the
            preprocessing itself.

        The function of PCPP is to write a preprocessed file ("filename.i",
            typically), such that if this file is given to another compiler,
            that compiler can skip translation phase 4 and generate the
            identical sequence of preprocessor tokens as it would have from
            the original source file(s) with preprocessing.

        The output file needs to have the same tokens, in textual form, as
        come from the input.  It doesn't matter if the original spelling is
        preserved, as long as it lexes to the same token.  In particular,
        trigraphs and line splices can remain as they came out of phases 1 and
        2 (other than raw strings).

        PCPP will preserve leading indentation before all nonempty source
        lines, even if altered by macros.  Otherwise, whitespace is condensed
        to single space characters.

        PCPP must separate consecutive tokens with extra whitespace when this
        affects the result of lexing the output.  This can happen when macro
        expansion results in consecutive tokens which were not originally
        consecutive.  See
        https://gcc.gnu.org/onlinedocs/cppinternals/Token-Spacing.html for how
        GCC does this.

        PCPP also preserves the (presumed) file and line number for every line
        in the output so that it is the same as where the line originated.
        The presumed location can be altered by #line directives in the input.
        The output file will contain #line directives as needed.

        Blank lines in small groups will be output, but larger groups will
        result in a #line directive to set the new line number.

        The Source doesn't actually generate anything for blank lines.
        Rather, the first token on a physical line carries a TokenSepIndent to
        indicate the change in line.  However, within a function macro's
        argument list, there is no indent.


        Items written to output() are:
            * Actual input token values.  Most tokens are written, but not
              all.
            * Indentation.  Several spaces in front of a non-blank line.
            * Extra newlines.
            * #Line directives.

        '''

        def tokens(toks: TokIter) -> None:
            """ Write all the tokens. """

            nonlocal tok, outloc, callback

            # This peek runs the iterator until the first token (if any).
            # This includes the initialization code which creates a < top
            # level > Source.
            toks.peek()

            # First, expand any CPP_GROUP.
            toks = ungroup(toks)

            top = prep.currsource
            callback = self.callback = LocalCallback()
            outloc = OutLoc(top, callback)
            outlocs.append(outloc)

            # Separation to apply to next token
            sep: TokenPad = None

            # Loop over the input tokens.
            # - Any group has already been replaced with its members.
            # - A position change updates the current OutLoc.
            # - A sep accumulates consecutive seps.
            # - Handles a regular token and any preceding seps.
            #   - If output line number changed, write indent or #line.
            #   - Else write spacing based on sep and token.sep.
            #   - Write the token value.

            sep: TokenSep = TokenSepNone.instance

            for tok in toks:
                typ: TokType = tok.type

                if typ.marker:
                    # Don't write anything, but carry the separators over.
                    sep = tok.sep
                    if tok.sep_after:
                        sep += tok.sep_after
                    continue
                elif typ.number:
                    # CPP_NUMBER isn't a valid int or float, needs warning.
                    prep.on_warn_token(
                        tok, f'Invalid number: {show_quoted(tok.value)}')
                # Accumulate seps before the token.
                if tok.sep:
                    if sep:
                        sep += tok.sep
                    else:
                        sep = tok.sep

                prep.log.msg(f"Write token {tok!r}, "
                             f"sep {sep!r}", tok)
                token(tok, sep, prevtoks)
                sep = TokenSepNone.instance
                # Get any sep after the token, to go before the next token.
                if tok.sep_after:
                    sep = tok.sep_after

        @TokIter.from_generator
        def ungroup(toks: TokIter) -> Iterator[PpTok]:
            """ Recursively replace any CPP_GROUP token with its members. """
            for tok in toks:
                if tok.type.group:
                    yield from ungroup(tok.toks)
                else:
                    yield tok

        def linedir(lineno: int, filename: str, flag: OutPosFlag = None
                    ) -> str:
            """
            Format a #line directive with presumed line and file.  Optional
            position flag to use with gcc/clang simulation.
            """
            if not prep.line_directive:
                return
            flags: str = flag and flag.flags or ""
            file = prep.fix_path_sep(filename)
            dir = f"{prep.line_directive} {lineno} \"{file}\"{flags}"
            return dir

        def output(text: str) -> None:
            """
            Writes the given string to the output file.
            """
            out.write(text)
            out.flush()

        class LocalCallback(Callback):
            """ An object which can call functions in nonlocal scopes. """
            @property
            def outloc(self) -> OutLoc:
                return outloc

            def linedir(self, lineno: int, filename: str,
                           flag: ChangePosFlag = None
                           ) -> str:
                """ Format a #line directive. """
                return linedir(lineno, filename=filename, flag=flag)

            def push(self, loc: OutLoc) -> None:
                """ Enter a new outloc. """
                nonlocal outloc
                outloc = loc
                outlocs.append(loc)

            def pop(self) -> OutLoc:
                """ Return to previous outloc. """
                nonlocal outloc
                outlocs.pop()
                outloc = outlocs.top()
                return outloc

            def newloc(self, source: Source) -> OutLoc:
                """ Creates a new OutLoc for the source file. """
                return OutLoc(source, callback)
                ...

            def output(self, text: str) -> None:
                """ Write the text, nothing else. """
                output(text)

            def avoid_paste(self) -> bool:
                """ True if space required between current token and previous.
                """
                return avoid_paste()

        def token(tok: PpTok, sep: TokenSep, prevtoks: PrevToks
                  ) -> None:
            """ Write whatever is required by the given token. """
            typ: TokType = tok.type
            if not typ.norm:
                if (typ.newpos):
                    outloc.change_loc(tok=tok, src_lineno=tok.lineno)
                    return
            # Anything else.
            outloc.token(tok, sep)
            if sep.indent:
                prevtoks.clear()
            prevtoks.push(tok)

        def avoid_paste() -> bool:
            """
            True if current tok requires a separating space to avoid paste.
            """
            prev: PpTok = prevtoks.prev
            if prev:
                if prev.pos == tok.prev:
                    return False
                ltype, rtype = prev.type, tok.type
                if rtype in ltype.sep_from:
                    test = ltype.sep_from[rtype]
                    if not test or test(
                            prevtoks.prev_prev, prev, tok):

                        prep.log.msg(f"Avoid paste of {prev!r} and {tok!r}",
                                     tok)
                        return True
            return False

        tokens(toks)
        # Output must end with a newline if it doesn't already.
        outloc.freshline()

    class PrevToks:
        """
        Holds the last two normal tokens, if any, seen since the start of
        the current line.
        """
        def __init__(self):
            self.clear()

        def clear(self) -> None:
            self.toks = [None, None]

        def push(self, tok: PpTok) -> None:
            self.toks = [self.toks[1], tok]

        @property
        def prev(self) -> PpTok | None:
            return self.toks[1]

        @property
        def prev_prev(self) -> PpTok | None:
            return self.toks[0]

        def __repr__(self):
            return f"{self.toks!r}"

    def __repr__(self):
        return f"<Writer {self.lexer}"


class Callback:
    """
    An object which can call functions in a Writer.
    A subclass implements this with nonlocal variables in a write() method.
    This class can be used as a do-nothing callback.
    """
    def linedir(self, lineno: int, filename: str,
                    flag: ChangePosFlag = None,
                    ) -> str:
        """ Format a #line directive. """
        pass

    def newloc(self, source: Source) -> OutLoc:
        """ Create new OutLoc for the source file. """
        pass

    def output(self, text: str) -> None:
        """ Write the text, nothing else. """
        pass


class OutLoc:
    """
    Tracks the presumed line number and filename for writing to the output.
    It manages all output belonging to a Source.

    The location state is made up of
        * The presumed line number.  Initially 1.
        * The presumed file name.  Initially same as that of the source.
        * Whether the current line is blank (so far).  Initially True.
        * Difference between source and presumed line numbers.

    The state is updated by various methods.  A callback object (usually)
    performs corresponding operations on the Writer so that the state will
    correspond to what is actually written.  The callback can be temporarily
    suppressed by a context manager nowrite() method.

    The state is affected by LocPosChange objects and anything else that
    writes to the output file.

    OutLoc also used to get values for __LINE__ and __FILE__ macro tokens at
    the current location in the source file.
    """

    # Set by the constructor...
    source: Source                  # The Source.
    writer: Callback                # Performs operations on the writer.
    prep: Preprocessor              # The preprocessor object.
    # Change by various methods...
    lineno: int                     # Current line in output.
    spaces: int = 0                 # Whitespace waiting to be written.
    blank: bool                     # Nothing written yet to current line.
    addline: int = 0                # Diff between output and source.
    filename: str                   # Output filename.
    movetok: PpTok = None           # Moving to this token.

    def __init__(self, source: Source, writer: Callback):
        self.source = source
        source.outloc = self
        self.writer = writer
        self.prep = source.prep
        self.lineno = 1
        self.blank = True
        self.addline = 0
        self.filename = source.filename

    def __getitem__(self, src_lineno: int) -> int:
        """ Line number corresponding to a source line of some token. """
        return src_lineno + self.addline

    def __iadd__(self, lines: int) -> Self:
        """
        Advance given number of lines, can be negative.  Changes both
        self.src_lineno and self.lineno.
        """
        self.setline(self.lineno + lines)
        return self

    def __isub__(self, lines: int) -> Self:
        """
        Back up given number of lines, can be negative.  Changes both
        self.src_lineno and self.lineno.
        """
        return self

    def setline(self, lineno: int) -> None:
        if lineno != self.lineno:
            self.lineno = lineno
            self.blank = True

    def freshline(self) -> None:
        """ Advance to next line if current line is not blank. """
        if not self.blank:
            self.newline()

    def newline(self, count: int = 1) -> None:
        """
        Write one or more newlines, and adjust line number and blank.
        """
        self += count
        self.writer.output('\n' * count)

    def token(self, tok: PpTok, sep: TokenSep) -> None:
        """ Write token value in its proper location in the output. """
        if not tok.hide:
            # A top level token, supplies location.
            self.movetok = tok
            self._moveto(sep)
            del self.movetok
        #self.loc = tok.loc
        else:
            self._moveto(sep)
        self.output(tok.value, tok)

    def _moveto(self, sep: TokenSep) -> None:
        """ Move to where next token should be written. """
        sep.moveto(self)

    def indent(self, indent: TokLoc) -> None:
        movetok = self.movetok
        indent = movetok and movetok.loc or indent
        self._to_line(indent.output_lineno)
        self.spaces = indent.colno - 1

    def spacing(self) -> None:
        self.spaces = 1

    def avoid_paste(self) -> bool:
        return self.writer.avoid_paste()

    def output(self, text: str, tok: PpTok = None) -> None:
        """
        Write some text to the output file and adjust line number and blank.
        """
        if not text:
            self.spaces = 0
            return
        if self.spaces:
            self.writer.output(' ' * self.spaces)
            self.spaces = 0
        if tok and tok.type.chk_nl:
            newlines = text.count('\n')
            if newlines:
                if self.prep.lang.clang:
                    # clang doesn't adjust line number.
                    # It also duplicates newlines on platforms with CR/LF.
                    if tok.source.file:
                        line_endings = tok.source.file.line_endings
                        if len(line_endings) > 1:
                            text = text.replace(
                                '\n', '\n' * len(line_endings))
                else:
                    self.lineno += newlines
                    self.blank = text.endswith('\n')
        self.writer.output(text)
        self.blank = False

    def change_loc(self, *, tok: PpTok, src_lineno: int) -> None:
        """
        Handle a location change at given source location.  The token's newpos
        has details.  May change the writer's OutLoc (currently self), which
        may be self's parent, or a brand new OutLoc.
        """
        newpos = tok.newpos
        typ = tok.type
        flag = newpos.flag
        if flag.method:
            flag.method(self, tok=tok, src_lineno=src_lineno)

    def enter(self, *, tok: PpTok, src_lineno: int) -> None:
        """
        Execute a TokLocEnter.  Entering a new Source file.  Create a new
        OutLoc, which is pushed onto the outloc stack and becomes the current
        outloc.  Moves to given source line.  Writes a #line for line 1 of the
        new source.  Special behavior for the top level.
        """
        newpos = tok.newpos
        flag = newpos.flag
        source = newpos.source
        if source.parent.parent:
            self._to_src_line(src_lineno)
        else:
            flag = OutPosFlag.Nothing
        newloc: OutLoc = self.writer.newloc(source)
        newloc._linedir(flag=flag)
        self.writer.push(newloc)

    def leave(self, *, tok: PpTok, src_lineno: int) -> None:
        """
        Leaving an included Source file, changing to its parent OutLoc.
        Write #line for the current line and file of the parent.
        """
        newpos = tok.newpos
        flag = newpos.flag
        self.freshline()
        oldloc = self.writer.pop()
        oldloc.setline(newpos.lineno)
        oldloc._linedir(flag=flag)

    def move(self, *, tok: PpTok, src_lineno: int) -> None:
        """ Changing presumed line and possibly file in current OutLoc. """
        newpos = tok.newpos
        flag = newpos.flag
        # Write #line.
        if newpos.filename:
            self.filename = newpos.filename
        self.freshline()
        self.addline = newpos.delta_lineno
        self.lineno = self[src_lineno] + 1
        self._linedir(flag=flag)

    def _to_src_line(self, src_lineno: int = 1) -> None:
        """
        Move to start of given source line number.  If already there, do
        nothing, and output might have some text written already.
        """
        self._to_line(self[src_lineno])

    def _to_line(self, lineno: int = 1) -> None:
        """
        Move to start of given output line number.  If already there, do
        nothing, and output might have some text written already.
        """
        skip = lineno - self.lineno
        if 0 < skip <= 8:
            self.newline(skip)
        elif not skip:
            return
        else: self._linedir(lineno, self.filename)
        self.lineno = lineno
        self.blank = True

    def _linedir(self, lineno: int = None, filename: str = None,
                flag: OutPosFlag = None
                ) -> None:
        """ Write a #line directive for current location, option to specify
        different line or file.
        """
        self.freshline()
        if lineno is None: lineno = self.lineno
        self.output(
            self.writer.linedir(lineno, filename or self.filename, flag))
        self.freshline()
        self.lineno -= 1

    def brk(self) -> bool:
        """ Break condition for debugging. """
        return break_match(line=self.lineno,
                           file=self.source and self.source.filename,
                           )

    def __repr__(self) -> str:
        srcline = self.addline and f"{self.src_lineno}/" or ""
        file = self.filename
        if file != self.source.filename:
            file = os.path.basename(self.filename)
            file = f"{self.source}/{file!r}"
        else:
            file = str(self.source)
        if self.blank:
            if self.spaces:
                space = PpTok.Reprs.spacing
            else:
                space = PpTok.Reprs.nospace
        else:
            space = ''
        return f"{file}:{srcline}{self.lineno}{space}"
                

class OutPosChange:
    """
    A notice of change of output location within the output file.  It
    corresponds to
      (1) entering an included Source, at line 1.
      (2) leaving an included Source, returning to the including Source.
      (3) a #line directive.  Changes the presumed line number, and optionally
          changes the presumed filename.
    It results in writing a #line directive to the output.  Also contains a
    flag indicating which of the above cases it is, also used by gcc and clang
    in the output #line.
    """
    flag: OutPosFlag            # Set below in the constructor for the flag.
    enter: bool = False
    leave: bool = False
    move: bool = False

    # Optional attributes, varying with the subclass...
    filename: str = None    # If present, represents a new source.filename.
    lineno: int = None
    source: Source = None

    @property
    def enter(self) -> bool:
        """ Has Begin position in its file. """
        return self.flag is OutPosFlag.Enter

    @property
    def leave(self) -> bool:
        """ Has End position in its file. """
        return self.flag is OutPosFlag.Leave

    @property
    def move(self) -> bool:
        """ Has position in the same file. """
        return self.flag is OutPosFlag.Move

    def brk(self) -> bool:
        """ Break condition for debugging. """
        return break_match(line=self.lineno, file=self.filename)

    def __str__(self) -> str:
        name = f' -> "{self.filename}"' * bool(self.filename)
        source = f' "{self.source}"' * bool(self.source)
        lineno = f'{self.lineno}' * (self.lineno is not None)
        return (f"{lineno}{' *' * self.enter}"
                f"{source}{' *' * self.leave}"
                f"{name}"
                )

    def __repr__(self) -> str:
        return f"<{type(self).__name__} {self}>"


class OutPosEnter(OutPosChange):
    """ Notes entering a new source file. """
    enter: bool = True
    def __init__(self, source: Source):
        self.source = source


class OutPosLeave(OutPosChange):
    """ Notes leaving a source file and returning to the including file. """
    leave: bool = True
    def __init__(self, lineno: int):
        self.lineno = lineno


class OutPosFlag(enum.Enum):
    """ Where a location is with respect to the source file.
    The values correspond to what gcc or clang generates in a #line output.
    """
    Move =  '',     TokLocMove,     OutLoc.move
    Enter = ' 1',   OutPosEnter,    OutLoc.enter
    Leave = ' 2',   OutPosLeave,    OutLoc.leave
    Nothing = '',

    def __init__(self, flags: str, cls: Type[OutPosChange] = None,
                 method: Callable[[OutLoc, PpTok, int], None] = None):
        self.flags = flags
        self.cls = cls
        if cls:
            cls.flag = self
        if method:
            self.method = method

